### ISSUE TITLE
Console client crashes when checkModel fails for HHmodelica

### ISSUE THREAD

**Issue by CSchoel** [MopeSWTP-SS21/MopeSWTP#70]
## Steps to reproduce

* Start client, connect to server
* Add HHmodelica project to ModelicaPath
* Load HHmodelica using loadModel (option 4)
* Check HHmodelica using checkModel (option 5)

## Expected behavior

I would expect that HHmodelica can be loaded without issues. However, since there is a separate issue with that (https://github.com/CSchoel/hh-modelica/issues/1), which should be fixed separately, I will only report here how I suspect that the existing error should be handled:

Error should be reported on the console, but client should still be able to send other commands.

## Actual behavior

The following exception is thrown, preventing the client from executing any further commands:

```plain
<Exception in thread "main" java.util.InputMismatchException
        at java.base/java.util.Scanner.throwFor(Scanner.java:939)
        at java.base/java.util.Scanner.next(Scanner.java:1594)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
        at Client.ConsoleClientLauncher.ConsoleMenue(ConsoleClientLauncher.java:108)
        at Client.ConsoleClientLauncher.main(ConsoleClientLauncher.java:78)
```

**Comment by manuEbg** [comment]
Have you tried this in IntelliJ?

**Comment by CSchoel** [comment]
Nope, I performed all my tests directly from the bash. Do you think that IntelliJ would behave differently?
